### PR TITLE
Database setup description

### PR DESCRIPTION
**Pull request by eric1973**
The How-To setup of the database is not mentioned in the book.

### CODE REVIEW

**Comment by garymcleanhall** [comment]
Hi Eric, thanks for this!

I'll take a look as soon as possible.

**Comment by eric1973** [comment]
Hi Gary,

Great book! You are welcome,

Eric

On 13 Mar 2016, at 18:00, Gary McLean Hall <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Eric, thanks for this!

I'll take a look as soon as possible.

-

**Comment by garymcleanhall** [comment]
Hi Eric, could you rebase this to current master, please?

**Comment by eric1973** [comment]
Hi Gary,

You mean this (update fork from source)?

https://help.github.com/articles/syncing-a-fork/


I added in SingleResponsibilityPrincipleToAbstraction several changes (some in fork and some only commited in my local repo)

I hope that is no problem for merging my pull request changeset into your
master.

Sent from my iPhone

mit freundlichen Gr?ssen
Erich Brunner

On 22 Mar 2016, at 12:24, Gary McLean Hall <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Eric, could you rebase this to current master, please?

-

**Pull request closed without merging**
